name: taxonomy-binder
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
  - rust
  - pip
  - pip:
    - git+https://github.com/dib-lab/sourmash@add-taxonomy
  #- sourmash>=4.1.0,<5 
  - krona=2.8
  - pandas=1.2.4
